### ISSUE TITLE
Peer review de Franco y Luana :D

### ISSUE THREAD

**Issue by Franco1389** [CarlaArdiles/proyectoLiebre#1]
- [ ] 1. Cumple
- [ ] 2. Los artículos están centrados. Falta agregar el margin-bottom de 10px a los íconos
- [ ] 3. Cumple
- [ ] 4. Cumple
- [ ] 5. Cumple
- [ ] 6. Cumple
- [ ] 7. No cumple. El search-bar es un div, asi como los imputs
- [ ] 8. No cumple
- [ ] 9. Cumplió los items del peer review, aplica media queries, siendo una pagina responsive
- [ ] 10. Falta acomodar logo, search-bar y "Comprá en cuotas" en tablet y desktop. Agregar espaciado en los elementos del nav bar del header. Corregir el amontonamiento del precio y el descuento en los artículos. En el footer, colocar las secciones en formato flex, para completar los requerimientos de los micro desafíos; además, agregar márgenes a los distintos elementos

**Comment by CarlaArdiles** [comment]
realicé todos los cambios requeridos, gracias chicos.
