### ISSUE TITLE
Ajustar tamaño de lupa

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [CarlaArdiles/proyectoLiebre#2]
- Debe ajustar icono de lupa para que quede mejor visualmente en mobile.

- Debe centrar el texto "Compra en cuotas..." con su icono.

![image](https://github.com/CarlaArdiles/proyectoLiebre/assets/147005581/52371a97-3e55-4a67-9c15-e71c04d0a08b)

**Comment by CarlaArdiles** [comment]
ajustado
