### ISSUE TITLE
Ajustar hover en tarjeta de producto

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [CarlaArdiles/proyectoLiebre#3]
- Al hacer hover sobre la tarjeta debe mostrar info adicional del producto

- El icono del camion debe girar hacia arriba.

- Para lo anterior debe aplicarse con transiciones para que quede mejor a la vista del usuario. 

![image](https://github.com/CarlaArdiles/proyectoLiebre/assets/147005581/fad01f5f-fac2-4edb-ab70-8263d0b2df48)

**Comment by CarlaArdiles** [comment]
realizada
