### ISSUE TITLE
Ajustar ubicaciones de elementos

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [CarlaArdiles/proyectoLiebre#4]
- Deben ajustarse las posiciones de los elementos del header de la pagina.

![image](https://github.com/CarlaArdiles/proyectoLiebre/assets/147005581/3774a913-b92a-4d99-89e1-7830d9ecf36a)

**Comment by CarlaArdiles** [comment]
creo que lo ajusté correctamente profe, cualquier cosa me avisa
