### ISSUE TITLE
Ajustar posicionamiento de footer

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [CarlaArdiles/proyectoLiebre#6]
- Debe ajustarse posiciones de las secciones del footer para todos los anchos de dispositivos

![image](https://github.com/CarlaArdiles/proyectoLiebre/assets/147005581/5df7be89-4e01-48af-a61d-40e3d7abf987)

**Comment by CarlaArdiles** [comment]
realizado, ya se organiza en tres columnas, para el modelo Desktop.
